### PR TITLE
import vm_version_bsd_aarch64.cpp from openjdk-jdk11u

### PR DESCRIPTION
**Pull request by klaus4**
fix build errors (use of undeclared indetifiers),
didn't finish the build yet, `ll try later tonight..
`noticed that https://github.com/battleblow/jdk14u will probably also need this change .

### CODE REVIEW

**Comment by battleblow** [comment]
I wonder if we need a different change here.

src/hotspot/os_cpu/bsd_x86/vm_version_bsd_x86.cpp is just three #include lines
src/hotspot/os_cpu/linux_x86/vm_version_linux_x86.cpp is just three #include lines

Maybe this file should just be three include lines as well?

**Comment by klaus4** [comment]
> I wonder if we need a different change here.
> 
> src/hotspot/os_cpu/bsd_x86/vm_version_bsd_x86.cpp is just three #include lines
> src/hotspot/os_cpu/linux_x86/vm_version_linux_x86.cpp is just three #include lines
> 
> Maybe this file should just be three include lines as well?

Well, although your question is more to the original file author Mikael, I guess resetting this file to just 3 lines would mean a completely new implementation (or reorganization) of the bsd-aarch64 port. I would only see any sense in it if the port would not work or if there was another special reason for reworking ...     back on my machines now and try to compile until reaching  jdk14

**Comment by klaus4** [comment]
with this PR : 
root@generic:/usr/local/openjdk12 # uname -a
FreeBSD generic 13.0-CURRENT FreeBSD 13.0-CURRENT #19 71703cd8836-c267543(master): Fri Mar 20 23:34:10 UTC 2020     root@generic:/usr/obj/usr/src/arm64.aarch64/sys/GENERIC-NODEBUG  arm64
root@generic:/usr/local/openjdk12 # bin/java -version
openjdk version "12.0.2" 2019-07-16
OpenJDK Runtime Environment (build 12.0.2+10-3)
OpenJDK 64-Bit Server VM (build 12.0.2+10-3, mixed mode, sharing)

**Comment by battleblow** [comment]
Thanks.  I've recall how this works now, we deliberately put the BSD code into this file rather than inline it into the shared version.  I tested this on 12.1-STABLE as well and have merged it.  It'll need a patch in the openjdk12 port though, which should be simple to add.

**Pull request merged**
