### PR TITLE
Add Powerpc64 Support

### PR DESCRIPTION
**Pull request by lenoil98**
Adds support for powerpc64

### CODE REVIEW

**Comment by battleblow** [comment]
Thanks for this request.  My biggest question is what is the difference between this and the changes that got merged to openjdk11 for powerpc64 support?  I've locally cherry picked those into openjdk12, and I'd like to understand how to reconcile those changes with these since I'd like them to end up as similar as possible.

**Comment by lenoil98** [comment]
The differences between patches for jdk11 and jdk12 are below:

--- /usr/ports/java/openjdk11/work/openjdk-jdk11u-jdk-11.0.2-9-4/src/hotspot/os_cpu/bsd_ppc/orderAccess_bsd_ppc.hpp
+++ /usr/ports/java/openjdk12/work/openjdk-jdk12u-jdk-12-33-2/src/hotspot/os_cpu/bsd_ppc/orderAccess_bsd_ppc.hpp
@@ -85,7 +85,7 @@
 struct OrderAccess::PlatformOrderedLoad<byte_size, X_ACQUIRE>
 {
   template <typename T>
-  T operator()(const volatile T* p) const { register T t = Atomic::load(p); inlasm_acquire_reg(t); return t; }
+  T operator()(const volatile T* p) const { T t = Atomic::load(p); inlasm_acquire_reg(t); return t; }
 };
 
 #undef inlasm_sync
--- /usr/ports/java/openjdk11/work/openjdk-jdk11u-jdk-11.0.2-9-4/src/hotspot/os_cpu/bsd_ppc/os_bsd_ppc.cpp
+++ /usr/ports/java/openjdk12/work/openjdk-jdk12u-jdk-12-33-2/src/hotspot/os_cpu/bsd_ppc/os_bsd_ppc.cpp
@@ -394,7 +394,7 @@
       // SIGSEGV-based implicit null check in compiled code.
       else if (sig == SIGSEGV && ImplicitNullChecks &&
                CodeCache::contains((void*) pc) &&
-               !MacroAssembler::needs_explicit_null_check((intptr_t) info->si_addr)) {
+               MacroAssembler::uses_implicit_null_check(info->si_addr)) {
         if (TraceTraps) {
           tty->print_cr("trap: null_check at " INTPTR_FORMAT " (SIGSEGV)", p2i(pc));
         }
@@ -440,20 +440,6 @@
         return true;
       }
     }
-
-    // Check to see if we caught the safepoint code in the
-    // process of write protecting the memory serialization page.
-    // It write enables the page immediately after protecting it
-    // so we can just return to retry the write.
-    if ((sig == SIGSEGV) &&
-        // Si_addr may not be valid due to a bug in the bsd-ppc64 kernel (see comment above).
-        // Use is_memory_serialization instead of si_addr.
-        ((NativeInstruction*)pc)->is_memory_serialization(thread, ucVoid)) {
-      // Synchronization problem in the pseudo memory barrier code (bug id 6546278)
-      // Block current thread until the memory serialize page permission restored.
-      os::block_on_serialize_page_trap();
-      return true;
-    }
   }
 
   if (stub != NULL) {

Also added new file "jdk.hotspot.agent/share/classes/sun/jvm/hotspot/runtime/bsd_ppc64/BsdPPC64JavaThreadPDAccess.java"

**Comment by lenoil98** [comment]
Deltas in attached file.
Also added new file: 
src/jdk.hotspot.agent/share/classes/sun/jvm/hotspot/runtime/bsd_ppc64/BsdPPC64JavaThreadPDAccess.java

[Patches.txt](https://github.com/battleblow/openjdk-jdk12u/files/3124125/Patches.txt)

**Comment by battleblow** [comment]
> Deltas in attached file.
> Also added new file:
> src/jdk.hotspot.agent/share/classes/sun/jvm/hotspot/runtime/bsd_ppc64/BsdPPC64JavaThreadPDAccess.java
> 
> [Patches.txt](https://github.com/battleblow/openjdk-jdk12u/files/3124125/Patches.txt)

Thanks.  That looks relatively small, and one of them naturally comes about as part of the merge.

I'd like to push the changes that from openjdk11 so I can track that they have been merged and then let's apply these changes separately.  Does that sound reasonable?

**Comment by lenoil98** [comment]
Sounds good to me!

**Comment by battleblow** [comment]
> Sounds good to me!

Great!  I've pushed the changes from openjdk11.  Can you apply the extra changes, test the compilation and update the pull request?  Should the first of the changes in Patches.txt be merged back into openjdk11 as well?

**Comment by lenoil98** [comment]
Yes. If you merge those patches, I won't need to make any other changes.

**Pull request closed without merging**
